
# Create development builds
#
# Builds Android and iOS development builds for devices and simulators.
# Learn more: https://docs.expo.dev/develop/development-builds/introduction/
#
# Created by EAS CLI v23.0.0

name: Create development builds

on:
  push:
    branches: ['main']
  
jobs:
  android_development_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: development


